server:
  port: 8080

spring:

  application:
    name: verify_backend

  jdbc:
    template:
      query-timeout: 30000

  datasource:
    url: jdbc:postgresql://localhost:5432/verify
    username: verify
    password: verify
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      pool-name: verify_pool
      minimum-idle: 10

  servlet:
    multipart:
      enabled: true
      location: ${user.dir}/tmp/uploads
      file-size-threshold: 10MB
      max-file-size: 50MB
      resolve-lazily: false


logging:
  level:
    # Логирование SQL запросов
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    # Дополнительно: логирование транзакций (опционально)
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
    # Логирование ваших DAO/Repository классов (опционально)
    com.example.verify_backend.Repository: DEBUG